services:
  web_server:
    build: .
    ports:
      - ${WEB_SERVER_PORT}:3000
    depends_on:
      - database
    container_name: 2dam-booking-webserver
    working_dir: /web
    command: pm2-runtime start pm2.json
    volumes:
      - ./2dam_booking:/web
    environment:
      - TZ=Europe/Berlin
    restart: always
  database:
    image: yobasystems/alpine-mariadb:11.4.5
    container_name:  2dam-booking-db
    env_file: ./.env
    ports:
      - "2222:3306"
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=Europe/Berlin
    volumes:
     - ./data/db/mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:apache
    container_name: phpmyadmin
    restart: unless-stopped
    depends_on:
      - database
    environment:
      PMA_HOST: database                        # nombre del servicio de tu MySQL
      PMA_USER: ${MYSQL_USER}                   # opcional
      PMA_PASSWORD: ${MYSQL_PASSWORD}           # opcional
      UPLOAD_LIMIT: 256M
      # BLOWFISH_SECRET: "cambia-esto-a-una-cadena-larga-aleatoria"
    ports:
      - "8081:80"                               # acceso a phpMyAdmin en http://localhost:8081
    